// movies list
export const GET_MOVIES_INIT = 'GET_MOVIES_INIT';
export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS';
export const GET_MOVIES_ERROR = 'GET_MOVIES_ERROR';
// movie details
export const GET_MOVIE_DETAILS_INIT = 'GET_MOVIE_DETAILS_INIT';
export const GET_MOVIE_DETAILS_SUCCESS = 'GET_MOVIE_DETAILS_SUCCESS';
export const GET_MOVIE_DETAILS_ERROR = 'GET_MOVIE_DETAILS_ERROR';
// movie videos
export const GET_MOVIE_VIDEOS_INIT = 'GET_MOVIE_VIDEOS_INIT';
export const GET_MOVIE_VIDEOS_SUCCESS = 'GET_MOVIE_VIDEOS_SUCCESS';
export const GET_MOVIE_VIDEOS_ERROR = 'GET_MOVIE_VIDEOS_ERROR';

// shows list
export const GET_SHOWS_INIT = 'GET_SHOWS_INIT';
export const GET_SHOWS_SUCCESS = 'GET_SHOWS_SUCCESS';
export const GET_SHOWS_ERROR = 'GET_SHOWS_ERROR';
// show details
export const GET_SHOW_DETAILS_INIT = 'GET_SHOW_DETAILS_INIT';
export const GET_SHOW_DETAILS_SUCCESS = 'GET_SHOW_DETAILS_SUCCESS';
export const GET_SHOW_DETAILS_ERROR = 'GET_SHOW_DETAILS_ERROR';
// show videos
export const GET_SHOW_VIDEOS_INIT = 'GET_SHOW_VIDEOS_INIT';
export const GET_SHOW_VIDEOS_SUCCESS = 'GET_SHOW_VIDEOS_SUCCESS';
export const GET_SHOW_VIDEOS_ERROR = 'GET_SHOW_VIDEOS_ERROR';

// change init tab
export const CHANGE_TAB = 'CHANGE_TAB';
